
all:
	g++ main.cpp teacher.cpp lecture.cpp classroom.cpp schedule_db.cpp schedule_entry.cpp schedule_table.cpp schedule_random_table.cpp evaluation.cpp selection.cpp crossover.cpp mutation.cpp -o schedule -std=c++11 -g

clean:
	rm -rf schedule
